parameters:
  - name: name
    type: string
    default:
  - name: path
    type: string
    default:
  - name: feed
    type: string
    default:
  - name: author
    type: string
    default:
  - name: company
    type: string
    default:
  - name: description
    type: string
    default:

stages:
- stage: build_pwsh
  displayName: Build PowerShell module
  dependsOn: settings
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: build
    displayName: Build and publish
    steps:
      - task: PowerShell@2
        displayName: Build package
        inputs:
          filePath: $(System.DefaultWorkingDirectory)/build.ps1
          arguments: > 
            -name "${{ parameters.name }}"
            -path "${{ parameters.path }}"
            -version "$(Build.BuildNumber)" 
            -publish "$(Build.ArtifactStagingDirectory)"
            -company "${{ parameters.company }}"
            -author "${{ parameters.author }}"
            -description "${{ parameters.description }}"

      - task: NuGetCommand@2
        displayName: Upload to NuGet feed
        inputs:
          command: push
          packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
          publishVstsFeed: ${{ parameters.feed }}